### ISSUE TITLE
Unneeded empty lines in license text for LGPL-3.0-only

### ISSUE THREAD

**Issue by cordlandwehr** [spdx/LicenseListPublisher#61] opened 2020-02-19 17:55 UTC
The license text for LGPL-3.0-only contains unneeded empty lines, which are actually not displayed in the HTML version of the license: https://github.com/spdx/license-list-data/blob/master/text/LGPL-3.0-or-later.txt
For me it seems that line breaks from the LGPL-3.0 HTML page are considered by the conversion tool in the same way as <p> or <br /> tags, which leads to the strange result.

This issue was originally reported in the reuse tracker, adding a link for cross-referencing the issue: https://github.com/fsfe/reuse-tool/issues/178

**Comment by goneall** [comment] 2020-03-04 17:36
Here's a link to the source license XML: https://github.com/spdx/license-list-XML/blob/master/src/LGPL-3.0-only.xml

I wonder if this is caused by the extra paragraph tags within the item tags.

I am considering this a bug in the generation tool since it renders correctly in HTML, but it could be argued we should fix the source XML to remove the paragraphs.

**Comment by goneall** [comment] 2020-11-14 04:35
Resolved with PR #83

**Closed by goneall** 2020-11-14 04:35 UTC
