### ISSUE TITLE
crossRef to opensource.org/licenses/* have isLive: false

### ISSUE THREAD

**Issue by softmoth** [spdx/LicenseListPublisher#141] opened 2022-10-21 17:33 UTC
The cross references ("Other web pages for this license" on the web page) which refer to opensource.org/licenses/* are marked as "no longer live" (`isLive: false`).

The web site is live.

I expect the links to be live, or else an explanation of why they are being treated as dead, or for them to be culled completely. It is disconcerting to read "no longer live" on such a central information source.

Example:

- https://spdx.org/licenses/0BSD.html shows ` https://opensource.org/licenses/0BSD [no longer live] `
- https://github.com/spdx/license-list-data/blob/master/website/0BSD.json shows `isLive: false, isValid: true`
- https://opensource.org/licenses/0BSD is alive and well.

**Comment by goneall** [comment] 2022-10-21 17:57
Duplicate of https://github.com/spdx/license-list-XML/issues/1582 

It looks like I committed to creating a PR for a workaround.  I'll work on that over the next couple of days.

@swinslow - when do you plan to do another release of the license list?  It would be great to get this in before then.

**Comment by softmoth** [comment] 2022-10-21 18:41
Thank you! One thought I had would be to raise an exception if the number of dead links changes by X% or something. This would require keeping state of the previous successful build, but would prevent some infrastructure outage to impact large parts of the website. Just a thought.

**Closed** 2022-10-22 16:05 UTC
